# Generated by Django 3.2.16 on 2023-11-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'Компоненты',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
            ],
            options={
                'verbose_name': 'накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='Necessary_component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'нужный компонент',
                'verbose_name_plural': 'Нужные компоненты',
            },
        ),
        migrations.CreateModel(
            name='Service_center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('address', models.TextField()),
                ('phone', models.IntegerField(max_length=11)),
            ],
            options={
                'verbose_name': 'сервисный центр',
                'verbose_name_plural': 'Сервисные центры',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'склад',
                'verbose_name_plural': 'Склады',
            },
        ),
        migrations.CreateModel(
            name='Worker_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock')),
            ],
            options={
                'verbose_name': 'работник склада',
                'verbose_name_plural': 'Работники складов',
            },
        ),
        migrations.CreateModel(
            name='Supplyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='Количество')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.component')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='necessary_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.necessary_component'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.service_center'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock'),
        ),
        migrations.AddField(
            model_name='component',
            name='stocks',
            field=models.ManyToManyField(through='tables.Stock_component', to='tables.Stock'),
        ),
    ]
