# Generated by Django 3.2.16 on 2023-12-07 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock_component',
            options={'verbose_name': 'склад-компонент', 'verbose_name_plural': 'Склад-компоненты'},
        ),
        migrations.AlterModelOptions(
            name='supplyer',
            options={'verbose_name': 'поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='component',
            name='stocks',
            field=models.ManyToManyField(through='tables.Stock_component', to='tables.Stock', verbose_name='Склады'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.IntegerField(verbose_name='Кол-во'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='necessary_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.necessary_component', verbose_name='Необходимый компонент'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='service_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.service_center', verbose_name='Сервисные центры'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock', verbose_name='Склады'),
        ),
        migrations.AlterField(
            model_name='necessary_component',
            name='name',
            field=models.CharField(blank=True, max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='service_center',
            name='phone',
            field=models.IntegerField(verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='stock_component',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.component', verbose_name='Компонент'),
        ),
        migrations.AlterField(
            model_name='stock_component',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock', verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='supplyer',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.invoice', verbose_name='Накладная'),
        ),
        migrations.AlterField(
            model_name='supplyer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='worker_stock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.stock', verbose_name='Склад'),
        ),
    ]
